### ISSUE TITLE
默认打开文件夹路径在国服下会因为旧有32位客户端残留文件导致优先选取错误路径

### ISSUE THREAD

**Issue by 0kestrel** [MintNick/ESAM#2]
老司机这是默认直接打开/eve下的第一个文件夹吗

**Comment by mintnick** [comment]
是的，默认选择第一个文件夹，有多个同类文件夹时可以通过下拉菜单选择。
软件没有保存用户偏好的功能，比如：打开时是显示国服还是欧服、上一次选择的设置文件夹是哪一个，之前读取过的用户名等等
这么做的原因有几个
1.大部分情况下玩家只是隔段时间偶尔用一次
2.我不太想在本地保存额外的配置文件，只有一个exe文件更便于传播和理解
3.小部分有多个文件夹的情况，玩家自己清理一次就可以，不想增加复杂性
4.懒
