### ISSUE TITLE
关于esi问题

### ISSUE THREAD

**Issue by duanyiemo3** [MintNick/ESAM#3]
老哥国服好像没有给出怎么获取token的方法。我参考kb网的那个研究了一下但是有点问题还请赐教。
https://reg.163.com/open/oauth2/authorize.do?state=N0B2oCGG9nf1q8CTjBZcwMTHxWJt0ll1&redirect_uri=https%3A%2F%2Fmpay-web.g.mkey.163.com%2Flogin%2Foauth2%2Freverify%2Fcheck%3Fgame_id%3Daecfu6bgiuaaaal2-g-ma79&response_type=code&client_id=7014295958

这里的state是什么我猜测是时间base64 不知道对不对，后面的应该是权限啥的？实在是搞不明白 还望不吝解惑感谢。

**Comment by mintnick** [comment]
state是一串自定义随机string，用于和response比对，进行安全验证
官方说明：https://auth0.com/docs/secure/attack-protection/state-parameters
更多ESI文档：https://docs.esi.evetech.net/

因为这个问题和本软件无关，而且我也不太了解ESI授权的开发，就关闭这个issue了，有更多问题建议在相关社区询问。
